'use client';

import { useEffect, useState } from 'react';
import { generatePassportQrSvg } from '../qr';
import type { QrPresentationOptions } from '../types';

export interface PassportQrCodeProps {
  url: string;
  config: QrPresentationOptions;
  /** Precomputed markup for server-rendered contexts (public/print/export) — skips client generation entirely when given. */
  svgMarkup?: string;
  className?: string;
}

/**
 * Thin wrapper around the pure `generatePassportQrSvg` — every render
 * context funnels through that one function, either by passing a
 * server-precomputed `svgMarkup` or by letting this component generate it
 * client-side (the interactive editor, where the link changes live as
 * presentation controls change).
 */
export function PassportQrCode({ url, config, svgMarkup, className }: PassportQrCodeProps) {
  const [generated, setGenerated] = useState<string>(svgMarkup ?? '');

  useEffect(() => {
    if (svgMarkup) {
      setGenerated(svgMarkup);
      return;
    }
    let cancelled = false;
    generatePassportQrSvg(url, config).then((svg) => {
      if (!cancelled) setGenerated(svg);
    });
    return () => {
      cancelled = true;
    };
  }, [url, config, svgMarkup]);

  if (!config.enabled || !generated) return null;

  return (
    <div
      className={className}
      role="img"
      aria-label={`QR code linking to this passport: ${url}`}
      style={{ width: config.size, height: config.size }}
      // Trusted markup generated by our own `qrcode`-backed qr.ts, not user-supplied HTML.
      dangerouslySetInnerHTML={{ __html: generated }}
    />
  );
}
